// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxnqgtyqrcibkdknwxyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bnFndHlxcmNpYmtka253eHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTc5ODAsImV4cCI6MjA2NDI3Mzk4MH0.XgFlTUnp0Nmave_REtIK1gCJ1-3E3pvzeufOOhPWo10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);